### ISSUE TITLE
Set of gears

### ISSUE THREAD

**Issue by Vittaly76** [sinyavskiy-n/US_direct#1]
Добрый день!
Подскажите, а комплект шестерёнок и мотор от Шерпа мини и шерпа микро один и тот же? Например, вот такой подойдёт?
https://aliexpress.ru/item/1005002192629947.html?sku_id=12000019009849261&spm=a2g2w.productlist.search_results.9.32801dc48tnEF5

**Comment by n1ki-s** [comment]
@Vittaly76, здравствуйте, подойдёт. Я брал такой же, но его нужно будет чуть-чуть доработать напильником (убрать пластик белой шестерни с короткой стороны вала) моторы одинаковые

**Comment by Vittaly76** [comment]
Ок, спасибо! Можно ли эту модель распечатать ABS- ом? Или есть какой-то особенный смысл, почему он не подойдёт, и надо печатать именно PETG?

**Comment by n1ki-s** [comment]
@Vittaly76 я пробовал печатать из ABS GF4 и petg, разницы нет. Что есть под рукой, то и можно использовать. Если вы печатаете в термокамере что-то высокотемпературное, то лучше конечно из ABS

**Comment by Vittaly76** [comment]
Всё понял, спасибо!!! Пошёл закупаться и печатать :)
