### ISSUE TITLE
Значение шагов экструдера для конфига

### ISSUE THREAD

**Issue by Vittaly76** [sinyavskiy-n/US_direct#2]
Добрый день!
Подскажите, а какой значение кол-ва шагов на мм прописывать в конфиге. Планирую для начала запуститься на Cherry v2, в последующем возможно перейду на Klipper.

**Comment by n1ki-s** [comment]
@Vittaly76 Здравствуйте, в ближайшее время нет возможности узнать достоверно, но насколько я помню, игрался со значением 700. Более точно можно настроить сняв хотенд и выдавливая по 100мм. Далее измеряете длину получившегося отрезка и корректируете под свой принтер. Так же, насколько я помню, нужно инвертировать пин dir, делается это восклицательным знаком в названии пина (было "e.1!", будет "e.1")

**Comment by n1ki-s** [comment]
@Vittaly76 на клиппере все тоже самое, если конечно не будете менять значение деления шага

**Comment by Vittaly76** [comment]
Принято, спасибо!!
